//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="CorsicaWars", ConfigurationName="IRefereeContract")]
public interface IRefereeContract
{
    
    [System.ServiceModel.OperationContractAttribute(Action="CorsicaWars/IRefereeContract/Hello", ReplyAction="CorsicaWars/IRefereeContract/HelloResponse")]
    string Hello(string message);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IRefereeContractChannel : IRefereeContract, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class RefereeContractClient : System.ServiceModel.ClientBase<IRefereeContract>, IRefereeContract
{
    
    public RefereeContractClient()
    {
    }
    
    public RefereeContractClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RefereeContractClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RefereeContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RefereeContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string Hello(string message)
    {
        return base.Channel.Hello(message);
    }
}
